# 加载numpy库

In [3]:
import numpy as np

# 基本操作

In [3]:
x = np.ndarray([5, 5])

## 查看数组维度

In [4]:
x.ndim

2

## 查看数组维度大小

In [5]:
x.shape

(5, 5)

## 查看元素多少

In [6]:
x.size

25

## 查看元素数据类型

In [7]:
x.dtype

dtype('float64')

## 获取数据内存地址（一般不用）

In [8]:
x.data

# 创建数组对象

In [9]:
x = np.array([1, 2, 3])
print(x.ndim)
print(x.shape)

1
(3,)


In [13]:
x = np.zeros((2, 2))
print(x)

[[0. 0.]
 [0. 0.]]


In [15]:
x = np.ones((2, 2))
print(x)

In [39]:
x = np.empty((3, 4))
print(x)

[[4.6597403e-310 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [20]:
x = np.random.randn(25).reshape((5, 5))
print(x)

[[ 0.50797607 -0.68939587  1.49560506  0.46082704  0.86193998]
 [ 0.11229852 -0.91730948 -1.35152346  1.13747079 -1.28958206]
 [ 0.01477269 -1.85552951 -0.27363625  1.0023272  -0.48586366]
 [-1.47062172  0.61807924 -0.23523451 -0.67479992 -1.3165498 ]
 [-0.10963193  1.00700459 -0.33213094  0.48539696  0.55819823]]


# 操作数组对象

In [41]:
x = np.ones((3, 3))
print(x)
y = np.ones((3, 3)) * 2
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


堆叠两个矩阵

In [45]:
z = np.stack((x, y), axis=2)
print(z)
print(z.shape)

[[[1. 2.]
  [1. 2.]
  [1. 2.]]

 [[1. 2.]
  [1. 2.]
  [1. 2.]]

 [[1. 2.]
  [1. 2.]
  [1. 2.]]]
(3, 3, 2)


# 遮掩数组

使用`numpy.ma`模块实现Masked array

In [1]:
import numpy.ma as ma

In [5]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
ma.masked_where(x < 5, x)

masked_array(
  data=[[--, --, --],
        [--, 5, 6],
        [7, 8, 9]],
  mask=[[ True,  True,  True],
        [ True, False, False],
        [False, False, False]],
  fill_value=999999)

In [9]:
ma.masked_equal(x, 1)

masked_array(
  data=[[--, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],
  mask=[[ True, False, False],
        [False, False, False],
        [False, False, False]],
  fill_value=1)

# 基本代数运算

矩阵行列式

In [50]:
x = np.random.randn(9).reshape((3, 3))
np.linalg.det(x)

0.23368659882011433

In [51]:
np.linalg.norm(x, ord='fro')

1.5098292850340735

In [32]:
print(x + y)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [25]:
print(y**2)

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [31]:
print(np.matmul(x, y))
print(x.dot(y))

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
